/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoonsIndexRouteImport } from './routes/roons/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCadastrarRouteImport } from './routes/auth/cadastrar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoonsIndexRoute = RoonsIndexRouteImport.update({
  id: '/roons/',
  path: '/roons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastrarRoute = AuthCadastrarRouteImport.update({
  id: '/auth/cadastrar',
  path: '/auth/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/login': typeof AuthLoginRoute
  '/roons': typeof RoonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/login': typeof AuthLoginRoute
  '/roons': typeof RoonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/cadastrar': typeof AuthCadastrarRoute
  '/auth/login': typeof AuthLoginRoute
  '/roons/': typeof RoonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/cadastrar' | '/auth/login' | '/roons'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/cadastrar' | '/auth/login' | '/roons'
  id: '__root__' | '/' | '/auth/cadastrar' | '/auth/login' | '/roons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCadastrarRoute: typeof AuthCadastrarRoute
  AuthLoginRoute: typeof AuthLoginRoute
  RoonsIndexRoute: typeof RoonsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roons/': {
      id: '/roons/'
      path: '/roons'
      fullPath: '/roons'
      preLoaderRoute: typeof RoonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastrar': {
      id: '/auth/cadastrar'
      path: '/auth/cadastrar'
      fullPath: '/auth/cadastrar'
      preLoaderRoute: typeof AuthCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCadastrarRoute: AuthCadastrarRoute,
  AuthLoginRoute: AuthLoginRoute,
  RoonsIndexRoute: RoonsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
